const roadSigns = [
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },
    { title: "Stop", imagePath: "path/to/stop-sign.jpg" },
    { title: "Yield", imagePath: "path/to/yield-sign.jpg" },
    { title: "No Entry", imagePath: "path/to/no-entry-sign.jpg" },
    { title: "Speed Limit 50", imagePath: "path/to/speed-limit-50.jpg" },

    // Add more road signs as needed
];
export { roadSigns };
