const path = '.\\resource\\images\\';
const roadSigns = [
    // Road Signs Ireland
    { category: "Road Signs", title: "Dangerous corner ahead", imagePath: path + "sharp-curve-to-the-left.png" },
    { category: "Road Signs", title: "Roundabout ahead", imagePath: path + "roundabout.png" },
    { category: "Road Signs", title: "Mini-Roundabout ahead", imagePath: path + "Mini-roundabout-ahead-300x300.png" },
    { category: "Road Signs", title: "Merging Traffic", imagePath: path + "Merging-traffic.png" },
    { category: "Road Signs", title: "Two-way Traffic", imagePath: path + "Two-way-traffic.png" },
    { category: "Road Signs", title: "Dangerous bend ahead", imagePath: path + "Dangerous bend ahead.webp" },
    { category: "Road Signs", title: "Series of dangerous bends ahead", imagePath: path + "Series-of-dangerous-bends-ahead.webp" },
    { category: "Road Signs", title: "Series of dangerous corners ahead", imagePath: path + "Series-of-dangerous-corners-ahead.webp" },
    { category: "Road Signs", title: "Restricted headroom", imagePath: path + "Restricted-headroom.png" },
    { category: "Road Signs", title: "T-junction", imagePath: path + "T-junction-1.png" },
    // Junction Signs
    { category: "Junction Signs", title: "Crossroad", imagePath: path + "crossroads.png" },
    { category: "Junction Signs", title: "Side road", imagePath: path + "Sideroad.png" },
    { category: "Junction Signs", title: "T-junction", imagePath: path + "T-junction-1.png" },
    { category: "Junction Signs", title: "Y-junction", imagePath: path + "Y-junction-1.jpg" },
    { category: "Junction Signs", title: "Staggered crossroads", imagePath: path + "Staggered-crossroads.png" },
    // Advanced Warning Signs of Roads
    { category: "Advanced Warning Signs", title: "T-junction of a dual carriageway", imagePath: path + "T-junctions-of-a-dual-carriageway-300x300.png" },
    { category: "Advanced Warning Signs", title: "Crossroad with dual carriageway", imagePath: path + "Crossroads-with-dual-carriageway-300x300.png" },
    { category: "Advanced Warning Signs", title: "Crossroad", imagePath: path + "crossroads-1.png" },
    // General Warning Signs
    { category: "General Warning Signs", title: "Drive on left", imagePath: path + "Drive-on-left-2.png" },
    { category: "General Warning Signs", title: "Safe height plate", imagePath: path + "Safe-height-plate.png" },
    { category: "General Warning Signs", title: "Low-flying aircrafts", imagePath: path + "Low-flying-aircrafts-300x300.png" },
    { category: "General Warning Signs", title: "Road divides", imagePath: path + "Road-divides.png" },
    { category: "General Warning Signs", title: "Merging/diverging traffic", imagePath: path + "Merging-diverging-traffic-300x300.png" },
    { category: "General Warning Signs", title: "Dual carriage ends", imagePath: path + "Dual-carriage-ends.png" },
    { category: "General Warning Signs", title: "Traffic crossover ahead", imagePath: path + "Traffic-crossover-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Overhead electric cables", imagePath: path + "Overhead-electric-cables-1-300x300.png" },
    { category: "General Warning Signs", title: "Traffic signals ahead", imagePath: path + "Traffic-signals-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Pedestrian crossing ahead", imagePath: path + "Pedestrian-crossing-ahead.png" },
    { category: "General Warning Signs", title: "Slippery road ahead", imagePath: path + "Slippery-road-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Road narrows on both sides", imagePath: path + "Road-narrows-on-both-sides-300x300.png" },
    { category: "General Warning Signs", title: "Road narrows from left", imagePath: path + "Road-narrows-from-left-300x300.png" },
    { category: "General Warning Signs", title: "Road narrows from right", imagePath: path + "Road-narrows-from-right-300x300.png" },
    { category: "General Warning Signs", title: "Tunnel ahead", imagePath: path + "Tunnel-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Cyclists", imagePath: path + "Cyclists-300x300.png" },
    { category: "General Warning Signs", title: "Start of a passing lane", imagePath: path + "Start-of-a-passing-lane-300x300.png" },
    { category: "General Warning Signs", title: "Lane loss", imagePath: path + "Lane-loss.png" },
    { category: "General Warning Signs", title: "Start of a climbing lane", imagePath: path + "Start-of-a-climbing-lane.png" },
    { category: "General Warning Signs", title: "Loop road ahead", imagePath: path + "Loop-road-ahead-150x150.png" },
    { category: "General Warning Signs", title: "Sharp dip ahead", imagePath: path + "Sharp-dip-ahead.png" },
    { category: "General Warning Signs", title: "Series of bumps ahead", imagePath: path + "Series-of-bumps-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Sharp rise ahead", imagePath: path + "Sharp-rise-ahead.png" },
    { category: "General Warning Signs", title: "Wild animals ahead", imagePath: path + "Wild-animals-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Sheep", imagePath: path + "Sheep-300x300.png" },
    { category: "General Warning Signs", title: "Cattle and farm animals", imagePath: path + "Cattle-and-farm-animals-300x300.png" },
    { category: "General Warning Signs", title: "Accompanied horses and ponies", imagePath: path + "Accompanied-horses-and-ponies-300x300.png" },
    { category: "General Warning Signs", title: "Crosswinds", imagePath: path + "Crosswinds.png" },
    { category: "General Warning Signs", title: "Steep descent ahead", imagePath: path + "Steep-descent-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Steep ascent ahead", imagePath: path + "Steep-ascent-ahead-300x300.png" },
    { category: "General Warning Signs", title: "Danger of falling rocks", imagePath: path + "Danger-of-falling-rocks-300x300.png" },
    { category: "General Warning Signs", title: "Unprotected quay, canal or river", imagePath: path + "Unprotected-quay-canal-or-river.png" },
    { category: "General Warning Signs", title: "Level crossing ahead, guarded by gates or lifting barrier", imagePath: path + "Level-crossing-ahead-guarded-by-gates-or-lifting-barrier-300x300.png" },
    { category: "General Warning Signs", title: "Level crossing ahead, unguarded by gates or lifting barrier", imagePath: path + "Level-crossing-ahead-unguarded-by-gates-or-lifting-barrier-300x300.png" },
    { category: "General Warning Signs", title: "Level crossing ahead, guarded by gates or lifting barriers", imagePath: path + "Level-crossing-ahead-guarded-by-gates-or-lifting-barriers-300x300.png" },
    { category: "General Warning Signs", title: "Stop when lights are red", imagePath: path + "Stop-when-lights-are-red-1.png" },
    { category: "General Warning Signs", title: "Automatic level crossing ahead", imagePath: path + "Automatic-level-crossing-ahead-1.png" },
    { category: "General Warning Signs", title: "Chevron board (left)", imagePath: path + "Chevron-board-left.png" },
    { category: "General Warning Signs", title: "Chevron board (right)", imagePath: path + "Chevron-board-right-1.png" },
    // Tram Signs
    { category: "Tram Signs", title: "Tram lane crossing ahead", imagePath: path + "Tram-lane-crossing-ahead-300x300.png" },
    { category: "Tram Signs", title: "Tram lane warning signs for pedestrians (look left)", imagePath: path + "Tram-lane-warning-signs-for-pedestrians-look-left-1.png" },
    { category: "Tram Signs", title: "Tram lane warning signs for pedestrians (look both sides)", imagePath: path + "Tram-lane-warning-signs-for-pedestrians-look-both-sides-1.png" },
    { category: "Tram Signs", title: "Tram lane warning signs for pedestrians (look right)", imagePath: path + "Tram-lane-warning-signs-for-pedestrians-look-right.png" },
    { category: "Tram Signs", title: "Slippery for cyclists", imagePath: path + "Slippery-for-cyclists.png" },
    // Warning signs for schools and children
    { category: "Warning signs for schools and children", title: "School ahead", imagePath: path + "School-ahead-300x300.png" },
    { category: "Warning signs for schools and children", title: "School children crossing ahead", imagePath: path + "School-children-crossing-ahead.png" },
    { category: "Warning signs for schools and children", title: "Children crossing ahead (in residential areas)", imagePath: path + "Children-crossing-ahead.png" },
    //======================================= Warning signs for road work =======================================
    { category: "Road work Signs", title: "Road works ahead", imagePath: path + "Road-works-ahead-1-300x300.png" },
    { category: "Road work Signs", title: "One-lane crossover (out)", imagePath: path + "One-lane-crossover-out.png" },
    { category: "Road work Signs", title: "One-lane crossover (back)", imagePath: path + "Diamond_road_sign_one-lane_crossover_back.svg-300x300.png" },
    { category: "Road work Signs", title: "Move to right (one lane)", imagePath: path + "Move-to-right-one-lane-1.png" },
    { category: "Road work Signs", title: "Move to left (one lane)", imagePath: path + "Move-to-left-one-lane-1.png" },
    { category: "Road work Signs", title: "Move to right (two lanes)", imagePath: path + "Move-to-left-two-lanes-3.png" },
    { category: "Road work Signs", title: "Move to left (two lanes)", imagePath: path + "Move-to-right-two-lanes.png" },
    { category: "Road work Signs", title: "Obstruction between lanes", imagePath: path + "Obstruction-between-lanes-1.png" },
    { category: "Road work Signs", title: "End of obstruction between lanes", imagePath: path + "End-of-obstruction-between-lanes-2.png" },
    { category: "Road work Signs", title: "Start of central reserve or obstruction", imagePath: path + "Startofcentralreserve.png" },
    { category: "Road work Signs", title: "End of central reserve or obstruction", imagePath: path + "Endofobstructionbetweenlanes.png" },
    { category: "Road work Signs", title: "Lanes diverge at crossover", imagePath: path + "Lanes-diverge-at-crossover.png" },
    { category: "Road work Signs", title: "Lanes rejoin at crossover", imagePath: path + "Lanes-rejoin-at-crossover.png" },
    { category: "Road work Signs", title: "Two-lanes crossover (back)", imagePath: path + "Two-lanes-crossover-back-150x150.png" },
    { category: "Road work Signs", title: "Two-lanes crossover (out)", imagePath: path + "Two-lanes-crossover-out-1.png" },
    { category: "Road work Signs", title: "Single-lane (for shuttle working)", imagePath: path + "Single-lane-for-shuttle-working.png" },
    { category: "Road work Signs", title: "Two-way traffic", imagePath: path + "Two-way-traffic-1.png" },
    { category: "Road work Signs", title: "Road narrows from left", imagePath: path + "Road-narrows-from-left.png" },
    { category: "Road work Signs", title: "Road narrows from right", imagePath: path + "Road-narrows-from-right.png" },
    { category: "Road work Signs", title: "Road narrows on both sides", imagePath: path + "Road-narrows-on-both-sides.png" },
    { category: "Road work Signs", title: "Offside lane (of two) closed", imagePath: path + "Offside-lane-of-two-closed.png" },
    { category: "Road work Signs", title: "Nearside lane (of two) closed", imagePath: path + "a_3yPcS-300x300.png" },
    { category: "Road work Signs", title: "Offside lane (of three) closed", imagePath: path + "Offside-lane-of-three-closed.png" },
    { category: "Road work Signs", title: "Nearside lane (of three) closed", imagePath: path + "as-300x300.png" },
    { category: "Road work Signs", title: "Two offside lanes (of three) closed", imagePath: path + "Two-offside-lanes-of-three-closed.png" },
    { category: "Road work Signs", title: "Two nearside lanes (of three) closed", imagePath: path + "Two-nearside-lanes-of-three-closed.-Two-alternative-styles.png" },
    { category: "Road work Signs", title: "Offside lane (of four) closed", imagePath: path + "Offside-lane-of-four-closed-1.png" },
    { category: "Road work Signs", title: "Nearside lane (of four) closed", imagePath: path + "WK046-300x300.jpg" },
    { category: "Road work Signs", title: "Two offside lanes (of four) closed", imagePath: path + "Two-offside-lanes-of-four-closed-1.png" },
    { category: "Road work Signs", title: "Two nearside lanes (of four) closed", imagePath: path + "Two-nearside-lanes-of-four-closed-1.png" },
    { category: "Road work Signs", title: "Side road on left", imagePath: path + "Side-road-on-left-1.png" },
    { category: "Road work Signs", title: "Side road on right", imagePath: path + "Side-road-on-right-2.png" },
    { category: "Road work Signs", title: "Site access on left", imagePath: path + "Site-access-on-left-300x300.png" },
    { category: "Road work Signs", title: "Site access on right", imagePath: path + "ssfdf-300x300.png" },
    { category: "Road work Signs", title: "Temporary traffic signal ahead", imagePath: path + "Temporary-traffic-signal-ahead.png" },
    { category: "Road work Signs", title: "Flagman ahead", imagePath: path + "Flagman-ahead-300x300.png" },
    { category: "Road work Signs", title: "Slippery road", imagePath: path + "Slippery-road-300x300.png" },
    { category: "Road work Signs", title: "Loose chippings", imagePath: path + "Loose-chippings.png" },
    { category: "Road work Signs", title: "Queues likely", imagePath: path + "Queues-likely.png" },
    { category: "Road work Signs", title: "Hump or ramp", imagePath: path + "Hump-or-ramp.png" },
    { category: "Road work Signs", title: "Pedestrian cross to right", imagePath: path + "Pedestrian-cross-to-right-300x300.png" },
    { category: "Road work Signs", title: "Overhead electric cables", imagePath: path + "Overhead-electric-cables-2.png" },
    { category: "Road work Signs", title: "Pedestrian cross to left", imagePath: path + "Pedestrian-cross-to-left-300x300.png" },
    { category: "Road work Signs", title: "Uneven surface", imagePath: path + "Uneven-surface-3-300x300.png" },
    { category: "Road work Signs", title: "Detour ahead", imagePath: path + "Detour-ahead-1.png" },
    { category: "Road work Signs", title: "Detour to left", imagePath: path + "Detour-to-left-300x300.jpg" },
    { category: "Road work Signs", title: "Detour to right", imagePath: path + "Detour-to-right-300x300.jpg" },
    { category: "Road work Signs", title: "Road closed", imagePath: path + "Road-closed-300x300.jpg" },
    { category: "Road work Signs", title: "Diverted traffic left", imagePath: path + "Diverted-traffic-left.jpg" },
    { category: "Road work Signs", title: "Diverted traffic", imagePath: path + "Diverted-traffic-300x300.jpg" },
    { category: "Road work Signs", title: "Diverted traffic", imagePath: path + "Diverted-traffic.png" },
    { category: "Road work Signs", title: "Diverted traffic2", imagePath: path + "Diverted-traffic-1.png" },
    { category: "Road work Signs", title: "End of detour", imagePath: path + "End-of-detour-1.png" },
    { category: "Road work Signs", title: "Detour destination", imagePath: path + "Detour-destination-300x300.jpg" },
    // Informative Signs for work at road
    { category: "Informative Signs", title: "Distance", imagePath: path + "Distance-1.png" },
    { category: "Informative Signs", title: "Length", imagePath: path + "Length.png" },
    { category: "Informative Signs", title: "Direction", imagePath: path + "Direction-1.png" },
    { category: "Informative Signs", title: "Direction and distance", imagePath: path + "Direction-and-distance.png" },
    { category: "Informative Signs", title: "Slow", imagePath: path + "Go-mall-300x300.jpg" },
    { category: "Informative Signs", title: "End", imagePath: path + "Direction-and-distance-1.png" },
    { category: "Informative Signs", title: "Cautionary speed", imagePath: path + "Cautionary-speed-1.png" },
    { category: "Informative Signs", title: "Type of works", imagePath: path + "Type-of-works.png" },
    { category: "Informative Signs", title: "Use hard shoulder", imagePath: path + "Use-hard-shoulder.png" },
    { category: "Informative Signs", title: "Unfinished Road surface", imagePath: path + "Unfinished-road-surface-300x300.jpg" },
    { category: "Informative Signs", title: "Barrier board", imagePath: path + "Barrier-board-300x300.jpg" },
    { category: "Informative Signs", title: "Concealed Entrance", imagePath: path + "Concealed-Entrance-300x300.jpg" },
    { category: "Informative Signs", title: "Chevron board", imagePath: path + "Chevron-board-1.png" },
    { category: "Informative Signs", title: "Speed limit ahead", imagePath: path + "Speed-limit-ahead.png" },
    { category: "Informative Signs", title: "Unfinished Road Surface", imagePath: path + "Hard-shoulder-closed-1.png" },
    // Manual Signs for Traffic control at road
    { category: "Manual Signs for Traffic control", title: "Flagman ahead", imagePath: path + "Flagman-ahead-1-300x300.png" },
    { category: "Manual Signs for Traffic control", title: "Stop", imagePath: path + "Stop-300x300.png" },
    { category: "Manual Signs for Traffic control", title: "Either form of go can be used", imagePath: path + "Either-form-of-go-can-be-used-2.png" },
    { category: "Manual Signs for Traffic control", title: "Either form of téigh can be used", imagePath: path + "Either-form-of-teigh-can-be-used-1.png" },
    // Regulatory Traffic Signs
    { category: "Regulatory Traffic Signs", title: "Stop", imagePath: path + "Stop-1-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Yield", imagePath: path + "Yield-1.png" },
    { category: "Regulatory Traffic Signs", title: "School wardens stop sign", imagePath: path + "School-wardens-stop-sign-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Parking prohibited", imagePath: path + "Parking-prohibited.png" },
    { category: "Regulatory Traffic Signs", title: "No left turn", imagePath: path + "No-left-turn-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No entry or ‘No straight ahead’", imagePath: path + "No-entry-or-‘No-straight-ahead-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No right turn", imagePath: path + "No-right-turn-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Clearway", imagePath: path + "Clearway-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 30", imagePath: path + "Max-speed-limit-30kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 50", imagePath: path + "Max-speed-limit-50kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 60", imagePath: path + "Max-speed-limit-60kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 80", imagePath: path + "Max-speed-limit-80kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 100", imagePath: path + "Max-speed-limit-100kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Speed Limit 120", imagePath: path + "Max-speed-limit-120kmh-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No ridden or accompanied horses", imagePath: path + "No-ridden-or-accompanied-horses-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No bicycles", imagePath: path + "No-bicycles-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Maximum gross weight", imagePath: path + "No-entry-for-large-vehicles-by-reference-to-weight.png" },
    { category: "Regulatory Traffic Signs", title: "Maximum vehicle length", imagePath: path + "Maximum-vehicle-length-1.png" },
    { category: "Regulatory Traffic Signs", title: "No entry to vehicles", imagePath: path + "No-entry-to-vehicles-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Maximum vehicle width", imagePath: path + "Maximum-vehicle-width-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Maximum axle weight", imagePath: path + "Maximum-axle-weight-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No overtaking for three-axle vehicles", imagePath: path + "No-overtaking-for-three-axle-vehicles.png" },
    { category: "Regulatory Traffic Signs", title: "No horse carriages", imagePath: path + "No-horse-carriages-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Height restriction", imagePath: path + "Height-restriction-1-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No overtaking", imagePath: path + "No-overtaking-for-three-axle-vehicles-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "Taxi rank", imagePath: path + "Taxi-rank-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "No entry for large vehicles", imagePath: path + "No-entry-for-large-vehicles-by-reference-to-weight.png" },
    { category: "Regulatory Traffic Signs", title: "No U-Turn", imagePath: path + "No-U-Turn-300x300.png" },
    { category: "Regulatory Traffic Signs", title: "End of the restriction zone", imagePath: path + "End-of-the-restriction-zone.png" },
    { category: "Regulatory Traffic Signs", title: "Parking permitted", imagePath: path + "Parking-permitted.png" },
    { category: "Regulatory Traffic Signs", title: "Pedestrianised street", imagePath: path + "Pedestrianised-street.png" },
    { category: "Regulatory Traffic Signs", title: "Zonal restriction", imagePath: path + "Zonal-restriction-–-parking-of-large-vehicles.png" },
    { category: "Regulatory Traffic Signs", title: "Disc parking plate", imagePath: path + "Disc-parking-plate.png" },
    // Mandatory Turns at Junctions
    { category: "Mandatory Turns at Junctions", title: "Turn left ahead", imagePath: path + "Turn-left-ahead.webp" },
    { category: "Mandatory Turns at Junctions", title: "Turn right ahead", imagePath: path + "Turn-right-ahead.webp" },
    { category: "Mandatory Turns at Junctions", title: "Turn left", imagePath: path + "Turn-left.webp" },
    { category: "Mandatory Turns at Junctions", title: "Turn right", imagePath: path + "Turn-right.webp" },
    { category: "Mandatory Turns at Junctions", title: "Straight ahead", imagePath: path + "Straight-ahead.webp" },
    { category: "Mandatory Turns at Junctions", title: "Keep left", imagePath: path + "Keep-left.webp" },
    { category: "Mandatory Turns at Junctions", title: "Keep right", imagePath: path + "Keep-right.webp" },
    { category: "Mandatory Turns at Junctions", title: "Pass either side", imagePath: path + "Pass-either-side.webp" },
    { category: "Mandatory Turns at Junctions", title: "Mini roundabout", imagePath: path + "Mini-roundabout.webp" },
    // Other Manual Work Signs for work at road
    { category: "Other Manual Work Signs", title: "Stop", imagePath: path + "Stop-300x300.png" },
    { category: "Other Manual Work Signs", title: "Either form of go", imagePath: path + "Either-form-of-go-can-be-used-2.png" },
    { category: "Other Manual Work Signs", title: "Either form of téigh", imagePath: path + "Either-form-of-teigh-can-be-used-1.png" },
    { category: "Other Manual Work Signs", title: "No entry for pedestrians to tramway", imagePath: path + "No-entry-for-pedestrians-to-tramway.png" },
    { category: "Other Manual Work Signs", title: "No entry to goods vehicles", imagePath: path + "No-entry-to-goods-vehicles-by-reference-to-number-of-axles-300x300.png" },
    { category: "Other Manual Work Signs", title: "Contra flow bus lane", imagePath: path + "Contra-flow-bus-lane-1.png" },
    { category: "Other Manual Work Signs", title: "With flow bus lane on left", imagePath: path + "With-flow-bus-lane-on-left.png" },
    { category: "Other Manual Work Signs", title: "With flow bus lane on right", imagePath: path + "With-flow-bus-lane-on-right.png" },
    { category: "Other Manual Work Signs", title: "Tram lane on left", imagePath: path + "Tram-lane-on-left.png" },
    { category: "Other Manual Work Signs", title: "Tram lane on right", imagePath: path + "Tram-lane-on-right.png" },
    { category: "Other Manual Work Signs", title: "Start of cycle track", imagePath: path + "Start-of-cycle-track.png" },
    { category: "Other Manual Work Signs", title: "End of cycle track", imagePath: path + "End-of-cycle-track.png" },
    { category: "Other Manual Work Signs", title: "Tram only street ireland", imagePath: path + "Tram-only-street-ireland.png" },
    { category: "Other Manual Work Signs", title: "Turn back", imagePath: path + "Turn-back-1.png" },
    { category: "Other Manual Work Signs", title: "Bus only street", imagePath: path + "Bus-only-street.png" },
    { category: "Other Manual Work Signs", title: "Pedestrians and bicycles only", imagePath: path + "Pedestrians-and-bicycles-only-300x300.png" },
    { category: "Other Manual Work Signs", title: "Separate bicycle and pedestrian lanes", imagePath: path + "Separate-bicycle-and-pedestrian-lanes.png" },
    // Traffic Lane Signs
    { category: "Traffic Lane Signs", title: "Go (Lane open)", imagePath: path + "Go-Lane-open.png" },
    { category: "Traffic Lane Signs", title: "Stop (Lane closed)", imagePath: path + "Stop-Lane-closed.png" },
    { category: "Traffic Lane Signs", title: "Move into the right-hand lane", imagePath: path + "Move-into-the-right-hand-lane.png" },
    { category: "Traffic Lane Signs", title: "Move into the left-hand lane", imagePath: path + "Move-into-the-left-hand-lane-1.png" },
    // Advance Information Signs
    { category: "Advance Information Signs", title: "Motorway", imagePath: path + "Motorway-1.png" },
    { category: "Advance Information Signs", title: "National road", imagePath: path + "National-road.png" },
    { category: "Advance Information Signs", title: "Regional road", imagePath: path + "Regional-road.png" },
    { category: "Advance Information Signs", title: "National road", imagePath: path + "National-road1.png" },
    { category: "Advance Information Signs", title: "Lane destination sign", imagePath: path + "Lane-destination-sign.png" },
    { category: "Advance Information Signs", title: "Dublin Port Tunnel ahead", imagePath: path + "Dublin-Port-Tunnel-ahead.png" },
    // Advance Direction Signs
    { category: "Advance Direction Signs", title: "Motorway direction sign", imagePath: path + "Motorway-direction-sign.png" },
    { category: "Advance Direction Signs", title: "National road direction signs", imagePath: path + "National-road-direction-signs.png" },
    { category: "Advance Direction Signs", title: "Regional road direction sign", imagePath: path + "Regional-road-direction-sign.png" },
    { category: "Advance Direction Signs", title: "Local road direction sign", imagePath: path + "Local-road-direction-sign.png" },
    { category: "Advance Direction Signs", title: "Town or village sign", imagePath: path + "Town-or-village-sign.png" },
    { category: "Advance Direction Signs", title: "Destination distance sign", imagePath: path + "Destination-distance-sign.png" },
    { category: "Advance Direction Signs", title: "Slow lane sign", imagePath: path + "Slow-lane-sign-1.png" },
    { category: "Advance Direction Signs", title: "Cul-de-sac", imagePath: path + "Cul-de-sac.png" },
    { category: "Advance Direction Signs", title: "Disabled persons parking bay", imagePath: path + "Disabled-persons-parking-bay.png" },
    { category: "Advance Direction Signs", title: "Airport symbol", imagePath: path + "Airport-symbol.png" },
    { category: "Advance Direction Signs", title: "Industrial estate symbol", imagePath: path + "Industrial-estate-symbol.png" },
    { category: "Advance Direction Signs", title: "Ferry symbol", imagePath: path + "Ferry-symbol-1.png" },
    { category: "Advance Direction Signs", title: "Alternative route for high vehicles", imagePath: path + "Alternative-route-for-high-vehicles.png" },
    { category: "Advance Direction Signs", title: "Lay-by ahead sign", imagePath: path + "Lay-by-ahead-sign-1.png" },
    { category: "Advance Direction Signs", title: "Hospital ahead sign", imagePath: path + "Hospital-ahead-sign-1.png" },
    { category: "Advance Direction Signs", title: "Lay-by sign", imagePath: path + "Lay-by-sign.png" },
    { category: "Advance Direction Signs", title: "Hospital sign", imagePath: path + "Hospital-sign.png" },
    { category: "Advance Direction Signs", title: "SOS lay-by", imagePath: path + "SOS-lay-by-1.png" },
    { category: "Advance Direction Signs", title: "Car park with facilities for disabled person", imagePath: path + "Car-park-with-facilities-for-disabled-person-1.png" },
    { category: "Advance Direction Signs", title: "Speed camera", imagePath: path + "Speed-camera-2.png" },
    { category: "Advance Direction Signs", title: "Advance information sign for low clearance", imagePath: path + "Advance-information-sign-for-low-clearance-1.png" },
    { category: "Advance Direction Signs", title: "Alternative route for heavy vehicles", imagePath: path + "Alternative-route-for-heavy-vehicles.png" },
    { category: "Advance Direction Signs", title: "Traffic calming sign", imagePath: path + "Traffic-calming-sign-1.png" },
    { category: "Advance Direction Signs", title: "Speed limit change ahead", imagePath: path + "Speed-limit-change-ahead.png" },
    // Motorway Signs
    { category: "Motorway Signs", title: "Motorway ahead", imagePath: path + "Motorway-ahead.png" },
    { category: "Motorway Signs", title: "Motorway ahead", imagePath: path + "Motorway-ahead-1.png" },
    { category: "Motorway Signs", title: "Advance direction sign", imagePath: path + "Advance-direction-sign-1.png" },
    { category: "Motorway Signs", title: "100m to next exit", imagePath: path + "100m-to-next-exit-1.png" },
    { category: "Motorway Signs", title: "200m to next exit", imagePath: path + "200m-to-next-exit-1.png" },
    { category: "Motorway Signs", title: "300m to next exit", imagePath: path + "300m-to-next-exit-1.png" },
    { category: "Motorway Signs", title: "The motorway ends 1km ahead", imagePath: path + "The-motorway-ends-1km-ahead-1.png" },
    { category: "Motorway Signs", title: "Motorway ends 500m ahead", imagePath: path + "Motorway-ends-500m-ahead.png" },
    { category: "Motorway Signs", title: "End of motorway", imagePath: path + "End-of-motorway-1.png" },
    { category: "Motorway Signs", title: "Route confirmatory sign for M7", imagePath: path + "Route-confirmatory-sign-for-M7.png" },
    { category: "Motorway Signs", title: "Advance direction for destination", imagePath: path + "Advance-direction-for-destination.png" },
    { category: "Motorway Signs", title: "Entry to motorway", imagePath: path + "Entry-to-motorway.png" },
    { category: "Motorway Signs", title: "Toll plaza ahead", imagePath: path + "Toll-plaza-ahead-1.png" },
    { category: "Motorway Signs", title: "Toll charges", imagePath: path + "Toll-charges.png" },
    { category: "Motorway Signs", title: "Toll plaza information sign", imagePath: path + "Toll-plaza-information-sign.png" },
    { category: "Motorway Signs", title: "Garda only", imagePath: path + "Garda-only-1.png" },
    { category: "Motorway Signs", title: "Authorized vehicles only", imagePath: path + "Authorized-vehicles-only.png" },
    { category: "Motorway Signs", title: "Typical 2km next exit sign", imagePath: path + "Typical-2km-next-exit-sign.png" },
    { category: "Motorway Signs", title: "Motorway service plaza", imagePath: path + "Motorway-service-plaza.png" },
    { category: "Motorway Signs", title: "Route confirmatory sign with Euro Route marker plate", imagePath: path + "Route-confirmatory-sign-with-Euro-Route-marker-plate.png" },
    { category: "Motorway Signs", title: "Typical lane gain sign", imagePath: path + "Typical-lane-gain-sign.png" },
];

export default roadSigns;